blog/urls.py
from django.urls import path

from . import views

app_name= 'blog'
urlpatterns =[
    path('',views.index, name = 'index'),
    path('<int:post_id>/',views.postpage, name ='postpage')
]

caglarbingol/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('home.urls')),
    path('blog/',include('blog.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path

from . import views

app_name= 'home'
urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
]

blog/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
import datetime

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=64)
    context = models.CharField(max_length=1500)
    date = models.DateTimeField()
    
    def __str__(self):
        return f"{self.title} to {self.context}"

class Category(models.Model):
    title = models.CharField(max_length=64)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.title

class Comment(MPTTModel):
    sender_name = models.CharField(max_length=64)
    context = models.CharField(max_length=500)
    date = models.DateTimeField()
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['-date']

    def __str__(self):
        return self.context

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.shortcuts import get_object_or_404,render
from django.template import loader
from .models import Comment, Post
import datetime
from django.urls import reverse

# Create your views here.
def index(request):
    latest_post_list = Post.objects.order_by('-date')[:5]
    context = {'latest_post_list': latest_post_list}
    return render(request, 'blog/index.html', context)

def postpage(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_id)
        sender_name = request.POST['sender_name']
        if not sender_name:
            return render(request, 'blog/postpage.html', {
                'post': post,
                'error_message': "Gonderici adi girilmedi. ",
            })
        comment = request.POST['comment']
        if not comment:
            return render(request, 'blog/postpage.html', {
                'post': post,
                'error_message': "Yorum girilmedi. ",
            })
        comment_id = request.POST['comment_id']
        parent = Comment.objects.get(pk=comment_id)
        if not parent:
            post.comment_set.create(sender_name= sender_name, context = comment , date = datetime.datetime.now())
        else:
            post.comment_set.create(sender_name= sender_name, context = comment , date = datetime.datetime.now(),parent= parent)
        #return render(request, 'blog/postpage.html', {'post': post})#
        return HttpResponseRedirect(reverse('blog:postpage', args=(post.id,)))
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/postpage.html', {'post': post})

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request,'home/index.html')

def about(request):
    return render(request,'home/about.html')

def portfolio(request):
    return render(request,'home/portfolio.html')

def contact(request):
    return render(request,'home/contact.html')

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block title %}
<title>Blog - Çağlar Bingöl</title>
{% endblock %}
{% block content %}
{% if latest_post_list %}
<div class="row col-12">
    {% for post in latest_post_list %}
    <div class="justify-content-center col-6">
        <div class="col-11 row">
            <h4><a href="{% url 'blog:postpage' post.id %}">{{ post.title }}</a></h4>
            <p>{{ post.context|slice:":150" }} ...</p>
            <div class="col-6">{{post.date}}</div>
            <div style="text-align:right;" class="col-6">{{post.comment_set.all|length}} Yorum</div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>Hic Blog Yazisi Bulunmamaktadir.</p>
{% endif %}

{% endblock %}

blog/templates/blog/postpage.html
{% extends 'base.html' %}
{% block title %}
<title>{{post.title}} - Çağlar Bingöl</title>
<style>
</style>
{% endblock %}
{% block content %}
<div class="col-12">
    <h1 style="text-align:center">
        {{ post.title}}
    </h1>
    <br>
    <p>
        &nbsp; {{ post.context }}
    </p>
    <br>
    <p>{% for category in post.category_set.all %}
        Kategoriler : {{ category.title }}
        {% endfor %}
    </p>
    <br>
    {% if error_message %}<p style="background-color: red;"><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'blog:postpage' post.id %}" method="post" id="usrform">
        {% csrf_token %}
        <textarea rows="4" cols="50" name="comment" form="usrform" class="form-control"
            placeholder="Yorum Giriniz."></textarea>
        <br>
        <input type="text" name="sender_name" class="form-control" placeholder="Kullanıcı Adı" aria-label="Username"
            aria-describedby="basic-addon1">
        <br>
        <input class="btn btn-primary" type="submit" value="Gönder">
    </form>
    <br>
    <p>
        {{post.comment_set.all|length}} Yorum:
    </p>

    {% load mptt_tags %}
    <ul style="list-style:none !important;">
        {% recursetree post.comment_set.all %}
    
        <li style="list-style:none !important;">
            {{node.sender_name}}: {{ node.context }}
            <br><br>
            <button class="btn" type="button" onclick="myFunction('{{node.context}}')">Cevapla</button>
            <br>
            <hr>
            <form style="display:none" action="{% url 'blog:postpage' post.id %}" method="post" id="{{ node.context }}">
                {% csrf_token %}
                <textarea style="display: none;" rows="4" cols="50" name="comment_id" form="{{ node.context }}" class="form-control"
                    placeholder="Yorum Giriniz.">{{node.pk}}</textarea>
                <textarea rows="4" cols="50" name="comment" form="{{ node.context }}" class="form-control"
                    placeholder="Yorum Giriniz."></textarea>
                <br>
                <input type="text" name="sender_name" class="form-control" placeholder="Kullanıcı Adı"
                    aria-label="Username" aria-describedby="basic-addon1">
                <br>
                <input class="btn btn-primary" type="submit" value="Gönder">
            </form>
            <br>
            {% if not node.is_leaf_node %}
            <ul class="children">
                {{ children }}
            </ul>
            {% endif %}
        </li>
        {% endrecursetree %}
    </ul>



</div>
<script>
    function myFunction(id) {
      var x = document.getElementById(id);
      if (x.style.display === "none") {
        x.style.display = "block";
      } else {
        x.style.display = "none";
      }
    }
    </script>
{% endblock %}

home/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    {% block title %}
    {% endblock %}
    <style>
        body {
            padding-top: 70px;
        }

        .navbar {
            height: 4.5%;
        }

        .nav-link {
            color: black !important;
            font-size: 0.9em !important;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="/">CAGLAR BINGOL <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/about"><i class="fa fa-user"></i> HAKKIMDA</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/portfolio"><i class="fa fa-th"></i> PORTFÖY</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/blog"><i class="fa fa-square-o"></i> BLOG</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/contact"><i class="fa fa-envelope"></i> İLETİŞİM</a>
                </li>
            </ul>
            <form class="form-inline my-0 my-lg-2">
                <input class="form-control form-control-sm mr-sm-4" type="search" placeholder="Ara" aria-label="Ara">
                <button class="btn btn-sm btn-primary my-2 my-sm-0" type="submit">Ara</button>
            </form>
        </div>
    </nav>
    <div class="container">
            <div class="row justify-content-center">
                {% block content %}
                {% endblock %}
            </div>

    </div>
</body>

</html>

home/templates/home/about.html
{% extends 'base.html' %}
{% block title %}
<title>Hakkımda - Çağlar Bingöl</title>
{% endblock %}
{% block bk %}

{% endblock %}
{% block content %}
<div class="col-12">
    <h3 class="text-center">HAKKIMDA</h3>
    <br>
    <p class="text-center"><em>Amacım aynı zamanda kişisel hobim olan mesleğimde gerekli yeteneklerimi geliştirip
        mesleğimde ilerleyerek mutlu bir hayat geçirmek.</em></p>
</div>
<p>Herkese merhaba. Ben Çağlar. 90 doğumluyum ve ailenin 98 yılına kadar en küçük çocuğuydum. Bu yüzden 90 gençliğinin
    trendleriyle büyüdüm. Lise öğretimimi İzmir’in ve Türkiye’nin sayılı liselerinden birisi olan Bornova Anadolu
    Lisesi’nde
    İngilizce bölümünde tamamladım. Küçük yaştan beri bilgisayarlarla aram iyiydi ve oyunların crack işlemini yapmayı
    öğrenmemle başlayan macerada önce fotmat atmayı öğrendim. Daha sonra bu merağım beni 2002 yılının aralığında PC
    world
    dergisini almaya yöneltti. PC World dergisinin arka sayfalarında bulunan donanım fiyatlarından kendi bilgisayarımın
    nasıl olması gerektiğiyle ilgili hayaller kurarken, kendimi ortaokul resim öğretmenimin (O zamanlar karakalemle de
    ilgilendiğim için öğretmenimle aram iyiydi.) bilgisayarını toplarken buldum. Devam eden süreçte yazılımla
    ilgilenmeye
    başladım fakat hem maddi yetersizlikler hem de dönemin kişisel sorunları bu ilgilimi ilerletmemi engelledi. Bu
    süreçte
    Linux işletim sistemiyle ve Özgür Yazılımla tanıştım. Lisenin son yıllarında meslek seçimi konusunda kararsızlıklar
    yaşadım. Makine mühendisliği dolu tercih formumu son gece bir çocukluk hastalığım olan bilgisayarlarla bağım kalması
    için Elektronik mühendisliğine çevirdim. Uludağ Üniversitesindeki hayatım yine maddi yetersizliklerle çok iyi
    başlamadı
    ve mezuniyet sürecim 2 yıl uzadı. Mezuniyetimin resmileşmesi ise staj bulma zorlukları sebebiyle yine 1 yıl uzadı.
    Şimdilerde geçmiş hayatımda iyi olduğum konuları Elektronik mühendisliği uzmanlığım olarak geri kalanları ise hobi
    olarak devam ettirmeye çalışmaktayım.
</p>
<div class="row">
    <div class="col-5 m6 text-center padding-large">
        <p><b><i class="fa fa-user margin-right"></i> Çağlar Bingöl</b></p><br>
        {% load static %}
        <img src="{% static 'home/images/caglarbingol.jpg' %}" style="width:300px;height:300px;" class=""
            alt="Photo of Me">
    </div>
    <!-- Hide this text on small devices -->
    <div class="col-7">
        <p> Bu siteyi kurma amacım ise üniversite yıllarında linux serverları (Apache, MySQL vs.) kurma çalışmalarımdan
            kalan bilgilerle yapabileceğimi düşünmemdi ve şuan burdasınız. Şuanda üzerinde çalıştığım konular HTML, CSS,
            Apache, PCB Tasarım Programları (Altium Designer, Eagle, KiCAD) üzerine sorularınız ve ya yardım isteğiniz
            olursa iletişim bilgilerinden bana ulaşabilirsiniz.</p>
    </div>
</div>

{% endblock %}

home/templates/home/contact.html
{% extends 'base.html' %}
{% block title %}
<title>İletişim - Çağlar Bingöl</title>
{% endblock %}
{% block bk %}
{% endblock %}
{% block content %}
<br>
<div class="row col-10">
    <div class="col-4 ">
        <div id="googleMap" class="rounded" style="width:100%;height:400px;"></div>
    </div>
    <div class="col-8">
        <div class="">
            <i class="fa fa-map-marker fa-fw "></i> İzmir, TR<br>
            <i class="fa fa-phone fa-fw "></i> Phone: +90 541 819 62 90<br>
            <i class="fa fa-envelope fa-fw"></i> Email:
            bingolcaglar@gmail.com<br>
        </div>
        <br>
        <p>Bana bir <i class="fa fa-coffee"></i> ısmarlamak, veya not bırakmak için:</p>
        <form action="" target="">
            <div class="row" style="margin:0 -16px 8px -16px">
                <div class="col-6">
                    <input class="form-control" type="text" placeholder="İsim" required name="Name">
                </div>
                <div class="col-6">
                    <input class="form-control" type="email" placeholder="Email" required name="Email">
                </div>
            </div>
            <input class="form-control" type="text" placeholder="Mesaj" required name="Message">
            <br>
            <button class="btn btn-primary" type="submit">
                <i class="fa fa-paper-plane"></i> GÖNDER
            </button>
        </form>
    </div>
</div>
<script>
    function myMap() {
        myCenter = new google.maps.LatLng(38.428114, 27.149798);
        var mapOptions = {
            center: myCenter,
            zoom: 12, scrollwheel: false, draggable: false,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("googleMap"), mapOptions);

        var marker = new google.maps.Marker({
            position: myCenter,
        });
        marker.setMap(map);
    }
</script>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZKF2esDzchOxwICQv9HIjXP3d1LJQAEc&callback=myMap"></script>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}
{% block title %}
<title>Ana Sayfa - Çağlar Bingöl</title>
{% load static %}
<style>
    body {
        background: white url("{% static 'home/images/img0.jpg' %}") no-repeat;
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        min-height: 100%;
    }
</style>
{% endblock %}
{% block bk %}

{% endblock %}
{% block content %}
{% endblock %}

home/templates/home/portfolio.html
{% extends 'base.html' %}
{% block title %}
<title>Portfolyo - Çağlar Bingöl</title>
{% endblock %}
{% block bk %}

{% endblock %}
{% block content %}


{% endblock %}